# Generated by Django 2.2.24 on 2021-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_confusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('admin', models.BooleanField(default=False)),
                ('teacher', models.BooleanField(default=False)),
                ('password', models.TextField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
