# Generated by Django 2.2.24 on 2021-12-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
