# Generated by Django 3.0 on 2021-12-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
