# Generated by Django 3.0 on 2021-12-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accountType',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
